// Generated by https://quicktype.io
export interface FetchOptions {}

export interface Client {
   endpoint: string;
   fetchOptions: FetchOptions;
}

export interface Pool {
   userPoolId: string;
   clientId: string;
   client: Client;
   advancedSecurityDataCollectionFlag: boolean;
   storage: { [key: string]: string };
}

export interface AccessTokenPayload {
   sub: string;
   'cognito:groups': string[];
   iss: string;
   version: number;
   client_id: string;
   origin_jti: string;
   token_use: string;
   scope: string;
   auth_time: number;
   exp: number;
   iat: number;
   jti: string;
   username: string;
}

export interface AccessToken {
   jwtToken: string;
   payload: AccessTokenPayload;
}

export interface Identity {
   userId: string;
   providerName: string;
   providerType: string;
   issuer: string;
   primary: string;
   dateCreated: string;
}

export interface IDTokenPayload {
   at_hash: string;
   sub: string;
   'cognito:groups': string[];
   iss: string;
   'cognito:username': string;
   nonce: string;
   origin_jti: string;
   aud: string;
   identities: Identity[];
   token_use: string;
   auth_time: number;
   exp: number;
   iat: number;
   jti: string;
}

export interface IDToken {
   jwtToken: string;
   payload: IDTokenPayload;
}

export interface RefreshToken {
   token: string;
}

export interface SignInUserSession {
   idToken: IDToken;
   refreshToken: RefreshToken;
   accessToken: AccessToken;
   clockDrift: number;
}

export interface LoginInterface {
   username: string;
   pool: Pool;
   Session: null;
   client: Client;
   signInUserSession: SignInUserSession;
   authenticationFlowType: string;
   storage: { [key: string]: string };
   keyPrefix: string;
   userDataKey: string;
}
