// Generated by https://quicktype.io

export interface GetLoginInterface {
  email: string;
  token: string;
  message: string;
  status: string;
  role: string;
}

export interface UserAuth {
  email: string;
  token: string;
}
