// Generated by https://quicktype.io

export interface IDTokenClaims {
    aud:                string;
    iss:                string;
    iat:                number;
    nbf:                number;
    exp:                number;
    aio:                string;
    name:               string;
    nonce:              string;
    oid:                string;
    preferred_username: string;
    rh:                 string;
    sub:                string;
    tid:                string;
    uti:                string;
    ver:                string;
}

export interface Account {
    homeAccountId:  string;
    environment:    string;
    tenantId:       string;
    username:       string;
    localAccountId: string;
    name:           string;
    idTokenClaims:  IDTokenClaims;
}

export interface Payload {
    authority:          string;
    uniqueId:           string;
    tenantId:           string;
    scopes:             string[];
    account:            Account;
    idToken:            string;
    idTokenClaims:      IDTokenClaims;
    accessToken:        string;
    fromCache:          boolean;
    expiresOn:          string;
    correlationId:      string;
    requestId:          string;
    extExpiresOn:       string;
    familyId:           string;
    tokenType:          string;
    state:              string;
    cloudGraphHostName: string;
    msGraphHost:        string;
    fromNativeBroker:   boolean;
}

export interface MSalInterface {
    eventType:       string;
    interactionType: string;
    payload:         Payload;
    error:           null;
    timestamp:       number;
}
