// Generated by https://quicktype.io

export interface RoutingData {
   Name: string;
   Language: string;
   Content: string;
   Description: string;
   RolloutFlag: string;
}

export interface RoutingInterface {
   success: boolean;
   message: string;
   data: RoutingData[];
}
