/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
   aws_project_region: 'us-west-2',
   aws_cognito_identity_pool_id: 'us-west-2:c81c9ebb-0de9-46b6-ad52-407db2170d95',
   aws_user_pools_id: 'us-west-2_tnF21pSSA',
   aws_user_pools_web_client_id: '6e86t9qc9i2kp48hanna2bfgi8',
   oauth: {
      domain: 'sync-dev.auth.us-west-2.amazoncognito.com',
      scope: ['email', 'openid'],
      redirectSignIn: 'http://localhost:3000',
      redirectSignOut: 'http://localhost:3000',
      // redirectSignIn: 'https://master.d3vq3ag4gelhp8.amplifyapp.com',
      // redirectSignOut: 'http://master.d3vq3ag4gelhp8.amplifyapp.com',
      responseType: 'code',
   },
   federationTarget: 'COGNITO_USER_POOLS',
};

export default awsExports;
