/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
    "aws_cognito_identity_pool_id": "us-west-2:c81c9ebb-0de9-46b6-ad52-407db2170d95",
    "aws_user_pools_id": "us-west-2_IcO8XLoKn",
    "aws_user_pools_web_client_id": "7454135d2for8o527g4te3fnb5",
    "oauth": {
      "domain": "sync-dev.auth.us-west-2.amazoncognito.com",
      "scope": ["email", "openid"],
      "redirectSignIn": "http://localhost:3000",
      "redirectSignOut": "http://localhost:3000",
      "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
  };
  
  export default awsExports;


// const awsmobile = {
//     "aws_project_region": "us-west-2",
//     "aws_cognito_identity_pool_id": "us-west-2:c81c9ebb-0de9-46b6-ad52-407db2170d95",
//     "aws_cognito_region": "us-west-2",
//     "aws_user_pools_id": "us-west-2_IcO8XLoKn",
//     "aws_user_pools_web_client_id": "7454135d2for8o527g4te3fnb5",
//     "oauth": {
//         "domain": "your_cognito_domain",
//     "scope": ["email", "openid", "profile"],
//     "redirectSignIn": "your_redirect_signin_url",
//     "redirectSignOut": "your_redirect_signout_url",
//     "responseType": "code"
//     },
//     "aws_cognito_username_attributes": [
//         "EMAIL",
//         "PHONE_NUMBER"
//     ],
//     "aws_cognito_social_providers": [],
//     "aws_cognito_signup_attributes": [
//         "EMAIL"
//     ],
//     "aws_cognito_mfa_configuration": "OFF",
//     "aws_cognito_mfa_types": [
//         "SMS"
//     ],
//     "aws_cognito_password_protection_settings": {
//         "passwordPolicyMinLength": 8,
//         "passwordPolicyCharacters": []
//     },
//     "aws_cognito_verification_mechanisms": [
//         "EMAIL"
//     ],
//     "REGION": "us-west-2",
//     "USER_POOL_ID": "6e86t9qc9i2kp48hanna2bfgi8",
//     "USER_POOL_APP_CLIENT_ID": "us-west-2_tnF21pSSA"
// };


// export default awsmobile;
